apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: django-verifications-runner
  namespace: github-runners

spec:
  replicas: 1
  template:
    spec:
      repository: pewresearch/django_verifications
      image: 458280294434.dkr.ecr.us-east-1.amazonaws.com/labs-actions-runner@sha256:3690cf91109f11ee61226125a4fe8cf34fd9ec55715084134524db32c7d3528b
      imagePullPolicy: Always
      serviceAccountName: labs-runner
      labels:
        - django-verifications-runner
      dockerEnabled: false
      dockerdContainerResources:
        limits:
          cpu: "4.0"
          memory: "8Gi"

        requests:
          cpu: "1.0"
          memory: "2Gi"

      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: labs-runner
              key: AWS_ACCESS_KEY_ID

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: labs-runner
              key: AWS_SECRET_ACCESS_KEY

    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
