# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_verifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='corrected',
            field=models.BooleanField(default=False),
        ),
    ]
