# Generated by Django 3.1.2 on 2020-10-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_verifications', '0002_verification_corrected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='is_good',
            field=models.BooleanField(null=True),
        ),
    ]
